### ISSUE TITLE
should the examples work? SetPindirsConsecutive instead of SetConsuecutivePindirs???

### ISSUE THREAD

**Issue by gherlein** [tinygo-org/pio#11]
I'm struggling to get the examples to work.  I changed line 11 in blink_pio.go to 

sm.SetPindirsConsecutive(pin, 1, true)

and I got it to work.  I suspect the API morphed after the examples were written?

**Comment by soypat** [comment]
Whoops! Yes you are correct, that was an outdated API. Thank you for submitting this issue! Fixed in latest commit to main
