### ISSUE TITLE
i2s: why is this build tag here limiting to go1.18

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/pio#13]
https://github.com/tinygo-org/pio/blob/27cbe9d986eb8305bc685962cf1154eaf2dcf0ab/rp2-pio/piolib/i2s.go#L1

Is this here for any actual reason, or was it just left in by accident?

**Comment by soypat** [comment]
The i2s implementation uses generics. This build tags allows using piolib with Go versions below 1.18
